### Forward Kinemetic

In [2]:

import modern_robotics.core as robot
import numpy as np


In [6]:
M = np.array([[-1, 0,  0, 0],
              [ 0, 1,  0, 6],
              [ 0, 0, -1, 2],
              [ 0, 0,  0, 1]])
Blist = np.array([[0, 0, -1, 2, 0,   0],
                  [0, 0,  0, 0, 1,   0],
                  [0, 0,  1, 0, 0, 0.1]]).T
thetalist = np.array([np.pi / 2.0, 3, np.pi])
print(M)
Fkin = robot.FKinBody(M, Blist, thetalist)

[[-1  0  0  0]
 [ 0  1  0  6]
 [ 0  0 -1  2]
 [ 0  0  0  1]]


### Open Chain Dynamics